default_install_hook_types: [pre-commit, pre-push]

repos:
# Use uv itself as a hook so the lock file never drifts
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.13
    hooks:
    -   id: uv-lock
    -   id: uv-export          # keeps requirements.txt fresh

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: requirements-txt-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-requests
        args: [--config-file=mypy.ini]

-   repo: local
    hooks:
    -   id: run-tests
        name: Run tests with coverage
        entry: uv run pytest tests --cov=repositories --cov=shared --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true
