name: Publish Package

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'  # Run when any tag starting with 'v' is pushed
  workflow_dispatch:  # Allow manual triggering

jobs:
  verify:
    name: Verify Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools_scm wheel
          pip install -e .

      - name: Verify package builds
        run: python -m build --sdist --wheel .

      - name: Run twine check
        run: twine check dist/*

  build-and-publish:
    name: Build and Publish Package
    needs: verify
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools_scm wheel

      - name: Determine version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: python -m build --sdist --wheel .

      - name: Run twine check
        run: twine check dist/*

      - name: Publish to Azure Artifacts
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          python -m pip config set global.extra-index-url https://pkgs.dev.azure.com/resumematchpro/resumematchpro/_packaging/resumematchpro/pypi/simple/
          echo "[distutils]" > ~/.pypirc
          echo "index-servers = azure" >> ~/.pypirc
          echo "[azure]" >> ~/.pypirc
          echo "repository = https://pkgs.dev.azure.com/resumematchpro/resumematchpro/_packaging/resumematchpro/pypi/upload" >> ~/.pypirc
          echo "username = azure" >> ~/.pypirc
          echo "password = ${AZURE_DEVOPS_PAT}" >> ~/.pypirc
          python -m twine upload --repository azure dist/*
